### ISSUE TITLE
Why is this a new repository (rather than an update to opsgenie/opsgenie-python-sdk)?

### ISSUE THREAD

**Issue by asqui** [opsgenie/opsgenie-python-sdk-v2#2]
I'm watching the opsgenie/opsgenie-python-sdk repository, expecting to see a new version there. Other developers probably are too.

Wouldn't it make more sense to put v2 of this SDK in this existing repository rather than creating a new one?

Should I duplicate issues raised previously (e.g. https://github.com/opsgenie/opsgenie-python-sdk/issues/7) here if I still think they should be addressed?

(The reason I raised #1 here is that I realised I only raised this in the Swagger project previously, not in opsgenie/opsgenie-python-sdk, but if you decide to go back to the other repo, then #1 should probably be re-raised there...)

**Comment by zfr** [comment]
Hi @asqui ,

At first, thanks for your valuable comments :)

We couldn't pay desired attention at Opsgenie Python SDK for a while. We're still evaluating our options, both Swagger and OpenAPI Generator. We didn't decide yet but votes are aligned with your thoughts right now :)

Why is there are 2 different repositories? Because we made several big decisions at the auto-generated code side. Also, we'll bring some nice features like:
- Configurable retry policy
- error-type header handling
- log support
- metric publish support
- short poll alert/incident APIs for async results
- etc.

Our V1 repo has 2 different approaches already:
- Auto-generated codes that come from Swagger
- hand-written old code blocks.

It would be really confusing for our contributors to have more than 2 different approaches at the same repository. And it is hard to maintain package/class hierarchies with the existing repo.

We'll start responding to V1 questions and want to direct the contributors to the new place. Before then, we need to finalize it at first ;)

**Comment by asqui** [comment]
Ok thanks for clarifying, that's helpful to understand.

To be honest I figured that the old style (non-Swagger) API (which has been deprecated for some years) would just be removed, and the newer Swagger API would receive breaking changes in line with changes to the Opsgenie REST API, which would be expected for a major version release.

So, for what it's worth, I still think it's reasonable to publish v2 in the same repo, if only for reasons of discoverability, and the avoidance of people accidentally picking up the old version and using it in the future.
